language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install: >
  pip install -r requirements.txt --use-mirrors &&
  sudo apt-get install redis-server &&
  sudo service redis-server start
script: >
  nosetests --version && nosetests
